### ISSUE TITLE
Deprecated format after upgrade to supervisor 2021.02.5

### ISSUE THREAD

**Issue by pvmil** [snowzach/hassio-addons#8]
After updating the HA Supervisor (from 2021.01.7 to 2021.02.5), I get the following warnings in the supervisor logging.
Can you please have a look at this?
(hope to have reported this in the correct repository)

WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of DOODS-amd64
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of DOODS-amd64
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of DOODS-cuda
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of DOODS-cuda
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of DOODS
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of DOODS

**Comment by snowzach** [comment]
Yep, I'll have a look. Thanks.

**Comment by frenck** [comment]
@snowzach <https://github.com/marketplace/actions/frenck-s-home-assistant-add-on-linter> Might be helpful.


```
# .github/workflows/lint.yaml
name: Lint
on: [push, pull_request]
jobs:
  build:
    name: Add-on configuration
    runs-on: ubuntu-latest
    strategy:
       matrix:
         addon: [doods-amd64, doods-cuda, doods, rts2p]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2
      - name: 🚀 Run Home Assistant Add-on Linter on ${{ matrix.addon }}
        uses: frenck/action-addon-linter@v2
        with:
          path: "./${{ matrix.addon }}"
```
